# Generated by Django 5.1 on 2024-09-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation')),
                ('updated', models.DateField(auto_now=True, verbose_name='Update')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ticker', models.CharField(max_length=10, verbose_name='Ticker')),
                ('periodicidade', models.IntegerField(verbose_name='Periodicidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço')),
                ('limite_inferior', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Inferior')),
                ('limite_superior', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Superior')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
    ]
