# Generated by Django 5.1 on 2024-09-08 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Update Day'),
        ),
    ]
