# Generated by Django 5.1 on 2024-09-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ativo_usuario_alter_ativo_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
    ]
