# Generated by Django 5.1 on 2024-09-16 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ativo_created_alter_ativo_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='limite_inferior',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='limite_superior',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='periodicidade',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='ativo',
            name='ticker',
            field=models.CharField(max_length=10, unique=True, verbose_name='Ticker'),
        ),
        migrations.CreateModel(
            name='AtivoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('periodicidade', models.IntegerField(verbose_name='Periodicidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço')),
                ('limite_inferior', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Inferior')),
                ('limite_superior', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Superior')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos_detalhes', to='core.ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativo_detalhes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalhe do Ativo',
                'verbose_name_plural': 'Detalhes dos Ativos',
            },
        ),
    ]
