# Generated by Django 5.1 on 2024-09-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ativo_limite_inferior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativodetalhe',
            name='preco',
        ),
        migrations.AddField(
            model_name='ativo',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
