# Generated by Django 5.1 on 2024-09-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ativodetalhe_preco_ativo_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativodetalhe',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
